config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"
  resources :projects do
    collection do
      get 'mypage'
      get 'draft_display'
      get 'posting_project'
      get 'done_project'
      get 'confirmation'
    end

    member do
      get 'display'
    end

    resources :drafts, only: [:new, :create]
    resources :executes, only: [:new, :create, :show, :edit, :update]
    resources :billings do
      member do
        get 'new_return1'
        get 'new_return2'
        get 'new_return3'
      end
      
      collection do
        post 'create_return1', to: 'billings#create_return1'
        post 'create_return2', to: 'billings#create_return2'
        post 'create_return3', to: 'billings#create_return3'
      end
    end

  end

  resources :cards, only: [:new, :index, :show] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/execute.rb
class Execute < ApplicationRecord
  validates :execute_title,
    length: {maximum: 40},
    presence: true
  validates :execute_image, presence: true
  validates :execute_text, presence: true
  

  belongs_to :user
  belongs_to :project

  mount_uploader :execute_image, ImageUploader
end

app/controllers/executes_controller.rb
class ExecutesController < ApplicationController
  before_action :set_project
  before_action :set_execute, only: [:show, :edit, :update]

  def new
    @execute = Execute.new
    # @executes = @project.executes.includes(:user)
  end

  def create
    @execute = Execute.create(execute_params)
    if  @execute.save
      redirect_to project_execute_path(@project, @execute.id) 
    else
      render :new
    end
  end

  def show
    @billings= Billing.where(project_id: @project.id)
  end

  def edit
  end

  def update
    if @execute.update(execute_params)
      redirect_to project_execute_path{@execute.id}
    else
      render :edit
    end
  end

  private

  def execute_params
    params.require(:execute).permit(:execute_title,:execute_image,:execute_text).merge(user_id: current_user.id, project_id: params[:project_id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_execute
    @execute = Execute.find(params[:id])
  end
  
  
end

app/views/executes/edit.html.haml
.contents-row
  
  .container__title 実行報告をする
  %hr.contents-line

  
  .project-configuration
    
    %h2.configuration 実行報告
    = form_with model: [@project, @execute], local: true do |form|
      
      %label.project__titles.box1 実行報告タイトル
      %span.Require 必須
      %p.return-expect （最大文字数：40文字まで）
      -# .error-box
      -#   = render partial: 'error-messages', locals: {user: @project, column: "title"}
      .box2= form.text_area :execute_title, class: "input" 
      
      .project__image.box1 実行報告画像
      %span.Require 必須
      -# .error-box
      -#   = render partial: 'error-messages', locals: {user: @project, column: "image"}
      .box2.box-upload
        %label
          = form.file_field :execute_image,  class: 'hidden-field6', id:  "input-file6"
          .image-box1
            = icon('far', 'image', class: 'Form__icon')
            %span.qulick1-1 クリックしてファイルをアップロード
      #preview6
        = image_tag @execute.execute_image.to_s, class:"resize-image6"
            
      .project__body.box1 実行報告本文
      %span.Require 必須
      -# .error-box
      -#   = render partial: 'error-messages', locals: {user: @project, column: "text"}
      .box2= form.text_area :execute_text, class: "input input3"
      
      .project__btn= form.submit "実行報告に戻る" ,class: "form-btn"

      .project__return__index
        =link_to "トップ画面へ戻る", root_path, class: "Payment__inner__add-btn"
      

app/views/executes/new.html.haml
.contents-row
  
  .container__title 実行報告をする
  %hr.contents-line

  
  .project-configuration
    
    %h2.configuration 実行報告
    = form_with model: [@project, @execute], local: true do |form|
      
      %label.project__titles.box1 実行報告タイトル
      %span.Require 必須
      %p.return-expect （最大文字数：40文字まで）
      -# .error-box
      -#   = render partial: 'error-messages', locals: {user: @project, column: "title"}
      .box2= form.text_area :execute_title, class: "input" 
      
      .project__image.box1 実行報告画像
      %span.Require 必須
      -# .error-box
      -#   = render partial: 'error-messages', locals: {user: @project, column: "image"}
      .box2.box-upload
        %label
          = form.file_field :execute_image,  class: 'hidden-field6', id:  "input-file6"
          .image-box1
            = icon('far', 'image', class: 'Form__icon')
            %span.qulick1-1 クリックしてファイルをアップロード
      #preview6
            
      .project__body.box1 実行報告本文
      %span.Require 必須
      -# .error-box
      -#   = render partial: 'error-messages', locals: {user: @project, column: "text"}
      .box2= form.text_area :execute_text, class: "input input3"
      
      .project__btn= form.submit "実行報告を投稿する" ,class: "form-btn"

      .project__return__index
        =link_to "トップ画面へ戻る", root_path, class: "Payment__inner__add-btn"
      

app/views/executes/show.html.haml
= render 'layouts/header'
.project
  .project__top
    実行報告
  %hr.contents-line
  .project__title
    .project__title__content
      .project__title__main
        = @project.title
      .project__title__name
        NAME:
        = @execute.user.nickname

    .project__excute
      .project__excute__amount
        目標金額:
        = @project.target_amount.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse 
        円
      .project__excute__total-amount
        支援総額:
        - total1 = @billings.sum(:count_1)
        - total2 = @billings.sum(:count_2)
        - total3 = @billings.sum(:count_3)
        - @total = total1*@project.return_price_1+total2*@project.return_price_2+total3*@project.return_price_3 
        =@total.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
        円
      .project__excute__image
        = image_tag @execute.execute_image.to_s, class: "image"
      .project__excute__report
        .project__excute__report__title
          = @execute.execute_title
        .project__excute__report__text.scroll
          =safe_join(@execute.execute_text.split("\n"),tag(:br))
  %hr.contents-line
  .project__excute__edit-btn

  -if user_signed_in? && current_user.id == @execute.user_id
    .project__execute-btn
      =link_to "編集する", edit_project_execute_path(@project.id), class: "form-btn"
  - else
    .project__execute-btn
  .project__return__index
    =link_to "トップ画面へ戻る", root_path, class: "Payment__inner__add-btn"

    