config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"
  resources :projects do
    collection do
      get 'mypage'
      get 'draft_display'
      get 'posting_project'
      get 'done_project'
      get 'confirmation'
    end

    member do
      get 'display'
    end

    resources :drafts, only: [:new, :create]
    resources :executes, only: [:new, :create, :show, :edit, :update]
    resources :billings do
      member do
        get 'new_return1'
        get 'new_return2'
        get 'new_return3'
      end
      
      collection do
        post 'create_return1', to: 'billings#create_return1'
        post 'create_return2', to: 'billings#create_return2'
        post 'create_return3', to: 'billings#create_return3'
      end
    end

  end

  resources :cards, only: [:new, :index, :show] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord

  validates :title,
    length: {maximum: 40},
    presence: true
  validates :image, presence: true
  validates :text, presence: true
  validates :profile, 
    length: {maximum: 1000},
    presence: true
  validates :profile_image, presence: true
  validates :target_amount,
  numericality: {only_integer: true, greater_than_or_equal_to: 10000, less_than_or_equal_to: 5000000},
  presence: true
  validates :tarm, presence: true
  validates :return_title_1,
    length: {maximum: 100},
    presence: true
  validates :return_price_1, 
  numericality: {only_integer: true, greater_than_or_equal_to: 500, less_than_or_equal_to: 100000},
  presence: true
  validates :return_title_2,
    length: {maximum: 100},
    presence: true
  validates :return_price_2, 
  numericality: {only_integer: true, greater_than_or_equal_to: 500, less_than_or_equal_to: 100000},
  presence: true
  validates :return_title_3,
    length: {maximum: 100},
    presence: true
  validates :return_price_3, 
  numericality: {only_integer: true, greater_than_or_equal_to: 500, less_than_or_equal_to: 100000},
  presence: true
  validate :finish_tarm_setting
  validate :first_tarm_setting
  # validatesではなくvalidateなので注意
  belongs_to :user
  has_one :draft
  has_one :execute
  has_many :billings
  mount_uploader :image, ImageUploader
  mount_uploader :profile_image, ImageUploader
  mount_uploader :return_image_1, ImageUploader
  mount_uploader :return_image_2, ImageUploader
  mount_uploader :return_image_3, ImageUploader

  def finish_tarm_setting
    errors.add(:tarm, "は最大180日間です") if tarm > Date.today + 180
  end

  def first_tarm_setting
    errors.add(:tarm, "を本日以降に設定してください") if Date.today >= tarm
  end

  



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require "date"
  before_action :set_project, only: [:show, :edit, :update, :display, :destroy]
  before_action :set_day, only: [:index, :show, :display, :posting_project, :done_project]
  


  def index
    @drafts = Draft.all
    @drafts.each do |draft|
      @projects = Project.where(id:draft.project_id)
      @projects.each do |project|
        @billings= Billing.where(project_id: project.id)
        total1 = @billings.sum(:count_1)
        total2 = @billings.sum(:count_2)
        total3 = @billings.sum(:count_3)
        @total = total1*project.return_price_1+total2*project.return_price_2+total3*project.return_price_3 
        @target_amount = project.target_amount
        @turm= project.tarm
      end
    end
  end

  def new
    @card = Card.find_by(user_id: current_user.id)
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
    if @card.blank?
      redirect_to confirmation_projects_path
    else
    customer = Payjp::Customer.retrieve(@card.customer_id)
    @default_card_information = customer.cards.retrieve(@card.payjp_id)
    end
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    if  @project.save
      redirect_to project_path(@project) 
    else
      render :new
    end
  end

  def show
    
    @billings= Billing.where(project_id: @project)
  end

  def display
    @billings= Billing.where(project_id: @project.id)
    @executes= Execute.where(project_id: @project.id)
  end

  

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to project_path{@project.id}
    else
      render :edit
    end
  end

  def mypage
  end

  def confirmation
  end

  def draft_display
    @projects = Project.where(user_id:current_user)
    @drafts = Draft.all
    @drafts.each do |draft|
      @rets = @projects.ids.reject {|v| v== draft.project_id}
      # prijectのidの中で、draft.project_idと一致しないものをrejectメソッドで抽出
      @projects = Project.where(id:@rets)
    end
    
  end

  def posting_project
    @drafts = Draft.where(user_id:current_user)
    @drafts.each do |draft|
      @projects = Project.where(id:draft.project_id )
      @projects.each do |project|
        @turm= project.tarm
      end
    end
  end

  def done_project
    @drafts = Draft.where(user_id:current_user)
    @drafts.each do |draft|
      @projects = Project.where(id:draft.project_id )
      @projects.each do |project|
        @turm= project.tarm
      end
    end
  end

  def destroy
    if @project.destroy
      redirect_to root_path 
    else
      render :show
    end
  end

  private
  def project_params
    params.require(:project).permit(:title,:image,:text,:profile,:profile_image,:target_amount,:tarm,:return_title_1,:return_price_1,:return_image_1,:return_title_2,:return_price_2,:return_image_2,:return_title_3,:return_price_3,:return_image_3).merge(user_id: current_user.id)
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def set_day
    @today = Date.today
  end
end

app/views/projects/_details.html.haml
.project__title
  .project__title__content
    .project__title__main
      = @project.title
    .project__title__name
      NAME:
      = @project.user.nickname

  .project__main
    .project__right
      - @target_amount = @project.target_amount
      - @turm= @project.tarm
      - total1 = @billings.sum(:count_1)
      - total2 = @billings.sum(:count_2)
      - total3 = @billings.sum(:count_3)
      - @total = total1*@project.return_price_1+total2*@project.return_price_2+total3*@project.return_price_3 
      - if @today >= @turm && @total >= @target_amount     
        .Achievement
          %span.trapezoid-display__achievement.fade-in01 達 成 
          %span.square-display__achievement.fade-in01 期間終了 
      - elsif @today >= @turm
        .Achievement
          %span.square-display__achievement.fade-in01 期間終了 
      - elsif @total >= @target_amount 
        .Achievement
          %span.trapezoid-display__achievement.fade-in01 達 成 
      - else
        .Achievement

      .project__right__image
        = image_tag @project.image.to_s, class: "image"

      .project__right__text.scroll
        %h2 プロジェクト詳細
        .project__right__text__detail
          =safe_join(@project.text.split("\n"),tag(:br))
      .project__right__profile
        %h2 Profile
        .project__right__profile__detail
          .profile-image
            = image_tag @project.profile_image.to_s, class: "image2"
          .profile-expect.scroll
            = @project.profile


    .project__left
      .project__left__contents
        .contents-total
          .contents-total__box1
            現在の支援総額
          .contents-total__box2
            =@total.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
            円

        .contents-pacent
          .contents-pacent__box1
            進捗率
          .contents-pacent__box2
            - @percent = number_to_percentage(@total.to_f/@project.target_amount*100,precision: 1)
            = @percent
            .contents-pacent__box2__graph1
              .contents-pacent__box2__graph2
                %input{name: "percent", type: "hidden", value:@percent, class: 'percent' }

        .contents-amount
          .contents-amount__box1.box
            目標金額
          .contents-amount__box2.box
            = @project.target_amount.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
            円
        .contents-turm
          .contents-turm__box1.box
            募集期間
          .contents-turm__box2.box
            = @project.tarm.strftime("%Y年%m月%d日")
            まで
      
      .project__left__return
        .project__left__return__title
          = icon('fas', 'gift',class: "icon")
          %p r e t u r n
        .return
          .return__title
            リターン①
          .return__price
            寄付金額：
            = @project.return_price_1.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
            円
          .return__content
            .return__image
              - if  @project.return_image_1.blank?
                = image_tag "/48094.jpg", alt: "プレゼント",  class: "nill_image"
              - else
                = image_tag @project.return_image_1.to_s, class: "image3"
            .return__text.scroll
              = @project.return_title_1
          .return__btn
            - if @today >= @project.tarm
              = link_to '募集期間終了', "#", class:'donate'
            - else
              - if user_signed_in? 
                - if current_user.id == @project.user_id
                  = link_to '寄付をする', "#", class:'donate'
                - else
                  = link_to '寄付をする', new_return1_project_billing_path(@project.id), class:'donate'
              - else
                = link_to '寄付をする', new_user_registration_path, class:'donate'
        .return
          .return__title
            リターン②
          .return__price
            寄付金額：
            = @project.return_price_2.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
            円
          .return__content
            .return__image
              - if  @project.return_image_2.blank?
                = image_tag "/48094.jpg", alt: "プレゼント",  class: "nill_image"
              - else
                = image_tag @project.return_image_2.to_s, class: "image3"
            .return__text.scroll
              = @project.return_title_2
          .return__btn
            - if @today >= @project.tarm
              = link_to '募集期間終了', "#", class:'donate'
            - else
              - if user_signed_in? 
                - if current_user.id == @project.user_id
                  = link_to '寄付をする', "#", class:'donate'
                - else
                  = link_to '寄付をする', new_return2_project_billing_path(@project.id), class:'donate'
              - else
                = link_to '寄付をする', new_user_registration_path, class:'donate'
        .return
          .return__title
            リターン③
          .return__price
            寄付金額：
            = @project.return_price_3.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
            円
          .return__content
            .return__image
              - if  @project.return_image_3.blank?
                = image_tag "/48094.jpg", alt: "プレゼント",  class: "nill_image"
              - else
                = image_tag @project.return_image_3.to_s, class: "image3"
            .return__text.scroll
              = @project.return_title_3
          .return__btn
            - if @today >= @project.tarm
              = link_to '募集期間終了', "#", class:'donate'
            - else
              - if user_signed_in? 
                - if current_user.id == @project.user_id
                  = link_to '寄付をする', "#", class:'donate'
                - else
                  = link_to '寄付をする', new_return3_project_billing_path(@project.id), class:'donate'
              - else
                = link_to '寄付をする', new_user_registration_path, class:'donate'

app/views/projects/_error-messages.html.haml
- if @project.errors.any?
  - unless @project.valid?
    - if errors = @project.errors.full_messages_for(column.to_sym)
      %ul
        - errors.each do |error|
          %li{style: "color:red"}=error

app/views/projects/confirmation.html.haml
= render 'layouts/header'
.Header-bar
%hr.contents-line
.Main-bar
  プロジェクトを投稿する前に以下をご確認ください。
  
    
  .Main-bar__page
    =link_to "ログイン未登録の方", new_user_registration_path, class: "link-title"
  .Main-bar__page
    =link_to "クレジット未登録の方", new_card_path, class: "link-title"

app/views/projects/display.html.haml
= render 'layouts/header'
.project
  .project__top
    Project
  %hr.contents-line
    = render "details"
  %hr.contents-line
  - @execute=Execute.where(project_id:@project.id)
  - if @execute.present? 
    .project__execute-btn
      =link_to "実行報告", project_execute_path(@project, @project.execute.id), class: "form-btn"
  - elsif @today >= @project.tarm && user_signed_in? && current_user.id == @project.user_id
    .project__execute-report
      %p.return-expect.red-color 期間が終了いたしました。
      %p.return-expect.red-color プロジェクトの実行報告を以下より投稿してください
    .project__execute-btn
      =link_to "実行報告をする", new_project_execute_path(@project.id), class: "form-btn"
    %hr.contents-line
  - else
    .project__return__index
      =link_to "トップ画面へ戻る", root_path, class: "Payment__inner__add-btn"

app/views/projects/done_project.html.haml
= render 'layouts/header'
.Header-bar
%hr.contents-line
.Mypage
  .Side-bar
    .Side-bar__image
    .Side-bar__name
      = "#{current_user.nickname} さん"
  .Main-bar
    .Main-bar__title
      完了したプロジェクト
    - @drafts = Draft.where(user_id:current_user)
    - @drafts.each do |draft|
      - @projects = Project.where(id:draft.project_id )
      - @projects.each do |project|
        - @turm= project.tarm
        - if @today >= @turm
          .Main-bar__detaile
            = link_to project_path(project.id), class: "link-title" do
              .Main-bar__detaile__image
                = image_tag project.image.to_s, class: "image"
              .Main-bar__detaile__box
                .Main-bar__detaile__box__title
                  =project.title
                .Main-bar__detaile__box__term
                  募集期間
                  = project.tarm.strftime("%Y年%m月%d日")
                  まで
                .Main-bar__detaile__box__pacent
                  進捗率
        - else
          
    .Main-bar__return
      =link_to "戻る", mypage_projects_path, class: "Payment__inner__add-btn"

app/views/projects/draft_display.html.haml
= render 'layouts/header'
.Header-bar
%hr.contents-line
.Mypage
  .Side-bar
    .Side-bar__image
    .Side-bar__name
      = "#{current_user.nickname} さん"
  .Main-bar
    .Main-bar__title
      下書き保存一覧
    - @projects.each do |project|
      .Main-bar__detaile
        = link_to edit_project_path(project.id), class: "link-title" do
          .Main-bar__detaile__image
            = image_tag project.image.to_s, class: "image"
          .Main-bar__detaile__box
            .Main-bar__detaile__box__title
              =project.title
            .Main-bar__detaile__box__term
              募集期間
              = project.tarm.strftime("%Y年%m月%d日")
              まで
            .Main-bar__detaile__box__pacent
              進捗率
    .Main-bar__return
      =link_to "戻る", mypage_projects_path, class: "Payment__inner__add-btn"
        

app/views/projects/index.html.haml
= render 'layouts/header'
.Phot
  .phot__image
    = image_tag '/Cat&Clover.jpg',class: "phot__image--background background-up"
    .expect.expect-1.fade-in-1
      %h2.expect__title.fade-in-2 
        ネコと人が
        %a共存
        できる世界のために
      
  .phot__image
    = image_tag '/rolling-cat.jpg',class: "phot__image--background background-up"
    .expect.expect-2
      %h2.expect__title 
        私たちができること・・・
      
  .phot__image
    = image_tag '/DowntownーCat.jpg',class: "phot__image--background"
    .phot__image__last
      #expect__title__crowdfunding
        保護猫 ✖︎ クラウドファンディング
      
      .Btn-box
        .Start-crowdfunding
          - if user_signed_in? 
            = link_to "クラウドファンディングをはじめる", new_project_path, method: :get, class: "select select-2"
          - else
            = link_to "クラウドファンディングをはじめる", confirmation_projects_path, method: :get, class: "select select-2"
        .Understand-crowdfunding
          = link_to "クラウドファンディングについて知る", "#", method: :get, class: "select select-2"        


  
.Body
  .Contents
    .Contents__expect
      .Contents__expect__title
        .Big-Tittle.About
          %p About
        %h1 保護ネコ活動✖︎クラウドファンディングについて
      .About-box
        .About-box__countent.About-box__flex
          .About-box__countent__message
            %p 現在、多くの保護団体や個人のボランティアの方々は
            %p 支援者の援助や自身の貯金を切り崩して
            %p 自身の生活を犠牲にして保護活動を行っています。
            %p そのような中、新型コロナウイルスによる影響により
            %p 保護ネコカフェの経営困難、譲渡会の中止など活動の継続が難しく、
            %p また運営資金の調達も今まで以上に厳しい状況となっています。
          .circle-cat
            = image_tag '/cat.svg',class: "icon-cat"
          .circle-money
            = image_tag '/money.svg',class: "icon-money"

        .About-box__grath
          .expect__box-2 
            .point
            %p 一匹のネコを保護するためにかかる費用
            %table
              %tr
              %th 避妊手術代
              %td 15,000~3,0000円
              %tr
              %th 健康診断
              %td 5,000~10,000円
              %tr
              %th 血液検査
              %td 4,000~10,500円
              %tr
              %th 入院料
              %td 2,000~5,000円
              %tr
              %th 予防接種料
              %td 4,000~6,000円
              %tr
              %th.totale 計
              %td.totale 30,000~61,500円
          .expect__ask-2
            %p 保護猫活動には非常にお金がかかります。
            %p この表は、一匹のネコを保護するためにかかる費用です。
            %p これらに加え、フードやネコ砂などの費用も加算されます。
            %p ひとつの命を守るだけでもこれだけのお金がかかります。
            %p 保護活動を行っている方々は活動と並行して
            %p 資金調達もしなければ活動を継続できません。
          
        .circle-inspiration
          = image_tag '/Inspiration-soft.svg',class: "icon-inspiration"

        .About-box__crowdfunding
          %p そこで、保護猫活動に興味を持っている多くのユーザーがネット上で気軽に募金ができる
          %p 保護ネコ活動専用のクラウドファンディングサイトを立ち上げることにいたしました！！
          %p このサイトを通して一つでも多くの小さな命が救われることを祈ります・・・
        .circle-handshake
          = image_tag '/handshake.svg',class: "icon-handshake"
        
   
    .Contents__expect.Contents__CrowdFunding
      .Contents__expect__title
        .Big-Tittle.CrowdFunding
          %p CrowdFunding
        %h1 クラウドファンディングとは
      .About-box
        .About-box__countent
          .About-box__countent__message
            %p クラウドファンディングとはインターネットを通して自分の活動を発信することで
            %p その活動を応援したいと思ってくれる人から資金を募るシステムのことです。
            
          .CrowdFunding-Box 
            .CrowdFunding-Box__base
              .point 
              %h2 投稿する
              %p 保護ネコを救うためのプロジェクトを投稿しプロジェクトに賛同していただいた方々に共に寄付を募ります。期間終了後は集まった寄付金を用いて行ったプロジェクトの実行報告を行います。 
              .Btn-box-2
                .Start-crowdfunding.btn-color
                  = icon('fas', 'angle-double-right')
                  - if user_signed_in? 
                    = link_to "クラウドファンディングをはじめる", new_project_path, method: :get, class: "select"
                  - else
                    = link_to "クラウドファンディングをはじめる", confirmation_projects_path, method: :get, class: "select"
            .CrowdFunding-Box__base
              .point
              %h2 寄付をする
              %p 支援をしたいプロジェクトに寄付をすることができます。
              %p 寄付金額は投稿者が設定しているリターンの種類から選択できます。寄付をしていただくと、投稿者からリターンとしてささやかなお礼が届きます。また、投稿者からの実行報告によって寄付金がどのように使用されたかを確認することができます。
    
    .Tag
      Let's Crowd Funding !!

    .Contents__projects
      - @drafts.each do |draft|
      - @projects = Project.where(id:draft.project_id)
        - @projects.each do |project|
        - @target_amount = project.target_amount
        - @turm= project.tarm
        - @billings= Billing.where(project_id: project.id)
        - total1 = @billings.sum(:count_1)
        - total2 = @billings.sum(:count_2)
        - total3 = @billings.sum(:count_3)
        - @total = total1*project.return_price_1+total2*project.return_price_2+total3*project.return_price_3 
        
          .Achievement
            - if @today >= @turm && @total >= @target_amount 
              %span.trapezoid.fade-in01 達 成 
              %span.square.fade-in01 期間終了 
            - elsif @today >= @turm
              %span.square.fade-in01 期間終了 
            - elsif @total >= @target_amount 
              %span.trapezoid.fade-in01 達 成 
            - else

            .Projects 
              = link_to display_project_path(project.id) , class: "Box3"do
                .Box1
                  = image_tag project.image.url.to_s, class: "Box1__image"
                .Box2
                  %p.Box2__title= project.title
                  %p.Box2__percent__contents 進捗率
                  - @percent = number_to_percentage(@total.to_f/project.target_amount*100,precision: 1)
                  = @percent
                  .contents-pacent__box2__graph1
                    .contents-pacent__box2__graph2
                      %input{name: "percent", type: "hidden", value:@percent, class: 'percent' }
                .Details
                  .Details__total.detail
                    %p 支援総額
                    - @billings= Billing.where(project_id: project.id)
                    - total1 = @billings.sum(:count_1)
                    - total2 = @billings.sum(:count_2)
                    - total3 = @billings.sum(:count_3)
                    - @total = total1*project.return_price_1+total2*project.return_price_2+total3*project.return_price_3 
                    =@total.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
                    円
                  .Details__suppoter.detail
                    %p 目標金額
                    = project.target_amount.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
                    円
                  .Details__term.detail
                    %p 募集期間
                    = project.tarm.strftime("%Y年%m月%d日")
                    まで
  
     
  
        

app/views/projects/mypage.html.haml
= render 'layouts/header'
.Header-bar
%hr.contents-line
.Mypage
  .Side-bar
    .Side-bar__image
    .Side-bar__name
      = "#{current_user.nickname} さん"
  .Main-bar
    .Main-bar__title
      プロジェクト
    .Main-bar__page
      =link_to "投稿中のプロジェクト", posting_project_projects_path, class: "link-title"
    .Main-bar__page
      =link_to "完了したプロジェクト", done_project_projects_path, class: "link-title"
    .Main-bar__page
      =link_to "下書き保存一覧", draft_display_projects_path, class: "link-title"
    .Main-bar__title.setting
      設定
    .Main-bar__page
      住所登録
    .Main-bar__page
      =link_to "クレジットカード登録", new_card_path, class: "link-title"
    .Main-bar__page
      =link_to "トップ画面へ戻る", root_path, class: "Payment__inner__add-btn"
      
      

app/views/projects/posting_project.html.haml
= render 'layouts/header'
.Header-bar
%hr.contents-line
.Mypage
  .Side-bar
    .Side-bar__image
    .Side-bar__name
      = "#{current_user.nickname} さん"
  .Main-bar
    .Main-bar__title
      投稿中のプロジェクト
    - @drafts.each do |draft|
      - @projects = Project.where(id:draft.project_id)
      - @projects.each do |project|
        - @turm= project.tarm
        - if @today < @turm
          .Main-bar__detaile
            = link_to project_path(project.id) ,class: "link-title" do
              .Main-bar__detaile__image
                = image_tag project.image.to_s, class: "image"
              .Main-bar__detaile__box
                .Main-bar__detaile__box__title
                  =project.title
                .Main-bar__detaile__box__term
                  募集期間
                  = project.tarm.strftime("%Y年%m月%d日")
                  まで
                .Main-bar__detaile__box__pacent
                  進捗率
        - else
    .Main-bar__return
      =link_to "戻る", mypage_projects_path, class: "Payment__inner__add-btn"
         

app/views/projects/show.html.haml
.project
  .project__top
    Project
  %hr.contents-line

    = render "details"

  %hr.contents-line
  .project-confirmation 
    %p.return-expect.confirmation 以上の内容でプロジェクトを開始してもよろしいですか？  
    %p.return-expect.red-color ※目標金額、募集期間、リターンの内容は開始後に変更はできません。
    .project-btn  
      .project-start.start
        - if @project.draft.blank?
          = link_to 'プロジェクトを開始する', project_drafts_path(@project,@draft), method: "post", class:'form-btn'
        - else
          = link_to '確定する', display_project_path(@project.id),  class:'form-btn'
      %hr.contents-line
      .project-start.wait
        = link_to '戻って修正する', edit_project_path, class:'form-btn edit-btn'
      .project-start
        - if @project.draft.blank?
          = link_to '下書き保存', draft_display_projects_path, class:'form-btn save-btn'
      .project-start
        - if @project.draft.blank?
          = link_to '削除する', project_path(@project.id), class:'form-btn delete-btn', method: :delete
  .project__return__index
    =link_to "トップ画面へ戻る", root_path, class: "Payment__inner__add-btn"

  




    
    