config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"
  resources :projects do
    collection do
      get 'mypage'
      get 'draft_display'
      get 'posting_project'
      get 'done_project'
      get 'confirmation'
    end

    member do
      get 'display'
    end

    resources :drafts, only: [:new, :create]
    resources :executes, only: [:new, :create, :show, :edit, :update]
    resources :billings do
      member do
        get 'new_return1'
        get 'new_return2'
        get 'new_return3'
      end
      
      collection do
        post 'create_return1', to: 'billings#create_return1'
        post 'create_return2', to: 'billings#create_return2'
        post 'create_return3', to: 'billings#create_return3'
      end
    end

  end

  resources :cards, only: [:new, :index, :show] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/billing.rb
class Billing < ApplicationRecord
  validates :count_1_or_count_2_or_count_3, presence: true

  belongs_to :user
  belongs_to :project

  private
    def count_1_or_count_2_or_count_3
      count_1.presence or count_2.presence or count_3.presence
    end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :set_card,:set_project
  before_action :new_return, only: [:new_return1, :new_return2, :new_return3]
  before_action :create_return, only: [:create_return1, :create_return2, :create_return3]

  def new_return1
  end

  def create_return1
  end

  def new_return2
  end

  def create_return2
  end

  def new_return3
  end

  def create_return3
  end


  private
  def billing_params
    params.require(:billing).permit(:count_1,:count_2,:count_3).merge(user_id: current_user.id, project_id: params[:project_id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def new_return
    @billing = Billing.new
    @billings = @project.billings.includes(:user)
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
    if @card.blank?
      redirect_to new_card_url 
    else
    customer = Payjp::Customer.retrieve(@card.customer_id)
    @default_card_information = customer.cards.retrieve(@card.payjp_id)
    end
  end

  def create_return
    @billing = Billing.create(billing_params)
    if  @billing.save 
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
      Payjp::Charge.create(
      amount: @project.return_price_1,
      customer: @card.customer_id, #顧客ID
      currency: 'jpy', #日本円
      )
      redirect_to display_project_path(@project.id) 
    end
  end


end

app/views/billings/_cardinfo.html.haml
%h2.Billing-Card 登録クレジットカード情報
.Billing-Card-Information
  .Billing-Information
    %label カード番号
    = "**** **** **** " + @default_card_information.last4
    %br
    %label 有効期限
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year
    %br

  = link_to 'クレジットカードを変更する', card_path, class:"card-change"

app/views/billings/new_return1.html.haml
.Donate
  .Donate__title プロジェクトに寄付をする
  %hr.contents-line

  
  
  .Donate-configuration
    %h2.configuration-verification 寄付内容の確認  
    .project__left__return
      .return
        .return__title.billing-return
          リターン①
        .return__price
          寄付金額：
          = @project.return_price_1.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
          円

        .return__content
          .return__image
            - if  @project.return_image_1.blank?
              = image_tag "/48094.jpg", alt: "プレゼント",  class: "nill_image"
            - else
              = image_tag @project.return_image_1.to_s, class: "image3"
          .return__text.scroll
            = @project.return_title_1 

    %hr.contents-line
    = render "cardinfo"

      
    .Form 
      = form_with model: [@project, @billing], url: create_return1_project_billings_path, local: true do |f|
        .Form__contents   
          = f.text_field :count_1, class: 'Form__count', type:'hidden', value:1
        .Form__btn 
        = f.submit "寄付をする",class:"donate billing_btn"


    

app/views/billings/new_return2.html.haml
.Donate
  .Donate__title プロジェクトに寄付をする
  %hr.contents-line

  
  
  .Donate-configuration
    %h2.configuration-verification 寄付内容の確認  
    .project__left__return
      .return
        .return__title
          リターン②
        .return__price
          寄付金額：
          = @project.return_price_2.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
          円
        .return__content
          .return__image
            - if  @project.return_image_2.blank?
              = image_tag "/48094.jpg", alt: "プレゼント",  class: "nill_image"
            - else
              = image_tag @project.return_image_2.to_s, class: "image3"
          .return__text.scroll
            = @project.return_title_2 

    %hr.contents-line
    = render "cardinfo"

    .Form 
      = form_with model: [@project, @billing], url: create_return2_project_billings_path, local: true do |f|
        .Form__contents   
          -# = @project.return_price_2
          -# 円 ✖︎
          = f.text_field :count_2, class: 'Form__count', type:'hidden', value:1
          -# 口 ＝
          -# %span#sales_commission_price
          -# 円 寄付する
        .Form__btn 
        = f.submit "寄付をする",class:"donate billing_btn"

app/views/billings/new_return3.html.haml
.Donate
  .Donate__title プロジェクトに寄付をする
  %hr.contents-line

  
  
  .Donate-configuration
    %h2.configuration-verification 寄付内容の確認  
    .project__left__return
      .return
        .return__title
          リターン③
        .return__price
          寄付金額：
          = @project.return_price_3.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
          円
        .return__content
          .return__image
            - if  @project.return_image_3.blank?
              = image_tag "/48094.jpg", alt: "プレゼント",  class: "nill_image"
            - else
              = image_tag @project.return_image_3.to_s, class: "image3"
          .return__text.scroll
            = @project.return_title_3 
            
    %hr.contents-line
    = render "cardinfo"

    .Form 
      = form_with model: [@project, @billing], url: create_return3_project_billings_path, local: true do |f|
        .Form__contents   
          -# = @project.return_price_3
          -# 円 ✖︎
          = f.text_field :count_3, class: 'Form__count', type:'hidden', value:1
          -# 口 ＝
          -# %span#sales_commission_price
          -# 円 寄付する
        .Form__btn 
        = f.submit "寄付をする",class:"donate billing_btn"