config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"
  resources :projects do
    collection do
      get 'mypage'
      get 'draft_display'
      get 'posting_project'
      get 'done_project'
      get 'confirmation'
    end

    member do
      get 'display'
    end

    resources :drafts, only: [:new, :create]
    resources :executes, only: [:new, :create, :show, :edit, :update]
    resources :billings do
      member do
        get 'new_return1'
        get 'new_return2'
        get 'new_return3'
      end
      
      collection do
        post 'create_return1', to: 'billings#create_return1'
        post 'create_return2', to: 'billings#create_return2'
        post 'create_return3', to: 'billings#create_return3'
      end
    end

  end

  resources :cards, only: [:new, :index, :show] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user 
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card, only: [:index, :new, :delete, :show]

  def index
  end

  def new
    redirect_to card_path(@card) if @card.present?
  end

  def pay #payjpとCardsテーブルへのcreate
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
    if params['payjp-token'].blank?
      redirect_to new_card_path 
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念のためmetadataにuser_idを入れたが、なくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, payjp_id: customer.default_card)
      if @card.save
        redirect_to root_path
      else
        redirect_to pay_cards_path
      end
    end
  end

  def delete #PayjpとCardsテーブルからの削除（destroy）
    if @card.blank?
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
    redirect_to cards_path
  end

  def show #Cardsのデータをpayjpに送り情報を取り出す
    if @card.blank?
      redirect_to new_card_url 
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.payjp_id)
    end
  end

  private
  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/views/cards/index.html.haml
= render 'layouts/header'
.Header-bar
%hr.contents-line
.Mypage
  .Side-bar
    .Side-bar__image
    .Side-bar__name
      = "#{current_user.nickname} さん" 
  .Main-bar
    .Main-bar__title
      支払い情報
    .Main-bar__contents
      .Information
        - if current_user.card
          = link_to "クレジットカード詳細", card_path(@card.id), method: :get, class: 'Payment__inner__add-btn'
        - else
          = link_to new_card_path, class: 'Payment__inner__add-btn' do
            -# = icon('far', 'credit-card')
            クレジットカードを登録する
                

app/views/cards/new.html.haml
-#トップページヘッダー
= render 'layouts/header'
.Header-bar
%hr.contents-line
.Mypage
  .Side-bar
    .Side-bar__image
    .Side-bar__name
      = "#{current_user.nickname} さん" 
  .Main-bar
    .Main-bar__title
      クレジットカード情報入力
    .Main-bar__contents 
      .Information
        = form_with url: pay_cards_path, method: :post, id: 'charge-form', name: "inputForm"  do |f|
          .CreditCard-Secondary
            %section.CreditCard-Number
              .CreditCard-Number__Zone
                .CreditCard-Number__Zone__Title
                  %label.box1 カード番号
                  %span.Require 必須
                  .CreditCard-Expiration
                    = f.text_field :number, name: "card_number", id:"card_number", type: "text", placeholder: '半角数字のみ', class: "input" , maxlength: "16"
              .CreditCard-Common
                .CreditCard-Common__Term
                  %label.box1 有効期限
                  %span.Require 必須
                .CreditCard-Expiration
                  = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]], {}, class: "input card-input" , name: "exp_year", id:"exp_month"
                  %span.CreditCard-Expiration 月
                  .CreditCard-Expiration__Time{"data-test": "card-expiry-yy"}
                    .CreditCard-Expiration__Time__Zone
                      = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029],["30",2030]], {}, class: "input card-input" , name: "exp_year", id:"exp_year"
                  %span.CreditCard-Expiration 年
              #card_token
                .CreditCard-Common
                  .CreditCard-Common__Text
                    %label.box1 セキュリティコード
                    %span.Require 必須
                  .CreditCard-Expiration
                    = f.text_field :cvc, name: "cvc", id:"cvc", class:"cvc", type: "text", placeholder: 'カード背面4桁もしくは3桁の番号', class: "input security-input" , maxlength: "4"
          .CreditCard-Common__Send  
            = f.submit "登録する", class: "Button",  id: "token_submit", "PAYJP_PUBKICK_KEY" => "pk_test_bd34a37047418348d799b0df"
                

app/views/cards/show.html.haml
= render 'layouts/header'
.Header-bar
%hr.contents-line
.Mypage
  .Side-bar
    .Side-bar__image
    .Side-bar__name
      = "#{current_user.nickname} さん" 
  .Main-bar
    .Main-bar__title
      登録クレジットカード情報
    .Main-bar__contents 
      .Information.Card-Information
        %label カード番号
        = "**** **** **** " + @default_card_information.last4
        %br
        %label 有効期限
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        = form_with url: delete_cards_path, method: :post, id: 'charge-form', name: "inputForm", local: true do |f|
          = f.submit "削除する", class: 'card-delete-btn'
        = link_to mypage_projects_path,  class: "Payment__inner__add-btn" do
          もどる